### ISSUE TITLE
Switch Pro Bluetooth Crashes Program

### ISSUE THREAD

**Issue by Blueueu** [robmikh/SoHConfig#2]
I've found that if you already have 4 SDL controller bindings already in place in the .ini, trying to connect SPECIFICALLY a NINTENDO SWITCH PRO CONTROLLER VIA BLUETOOTH will cause the program to crash. Switch Controller Pro via USB is fine, only crashes with Switch Pro Controller VIA BLUETOOTH!!

Deleting mappings manually in the .ini and having at most 2 seems to fix the issue. 

[soh_ini_4_SDL_controller_bindings.zip](https://github.com/robmikh/SoHConfig/files/8347541/soh_ini_4_SDL_controller_bindings.zip)

**Comment by robmikh** [comment]
Thanks for the repro! Looks like a very silly bug that requires multiple controller bindings in the ini file, and for a controller to connect that is the second to last (or earlier) controller listed.
