### ISSUE TITLE
CPU and Power usage randomly start going way up.

### ISSUE THREAD

**Issue by Newtype14** [robmikh/SoHConfig#3]
When you launch SoHConfig, CPU and power usage is normal, but at some point while using it, CPU usage more than quadruples and Power usage is Very high according to Task Manager. I can even hear my PC fans spinning faster to compensate. It never returns to normal until you close the app.

**Comment by robmikh** [comment]
Ah, that's probably the input thread. I guess I could throttle it or pause the thread while the window doesn't have focus.

**Comment by robmikh** [comment]
Actually, a better solution may be to use [`SDL_WaitEvent`](https://wiki.libsdl.org/SDL_WaitEvent). The semantics are closer to what we want, since the input thread doesn't do any other operations when pumping messages.

**Comment by robmikh** [comment]
Looks like that did the trick. Fixed with 8ea56026bc29906ef3131aebec8508c486308a63.
